version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./database:/app/database
    depends_on:
      - sqlite

  sqlite:
    image: alpine:latest
    volumes:
      - ./database:/data
    command: |
      sh -c "apk --no-cache add sqlite && \
      cp -n /data/initial-db.sqlite /data/db.sqlite && \
      sqlite3 /data/db.sqlite && \
      tail -f /dev/null"
